name: Run PHPCS, PHPLint, and Playwright

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PHPCS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Show PHPCS sniffs
        run: ./vendor/bin/phpcs -i
      - name: Show PHPCS version
        run: ./vendor/bin/phpcs --version
      - name: Run PHP_CodeSniffer
        run: composer phpcs

  PHPLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Show PHPLint version info
        run: ./vendor/bin/phplint --version
      - name: Run PHPLint
        run: composer phplint

  Playwright:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: pnpm i
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

